// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlympicGames.Models;

#nullable disable

namespace OlympicGames.Migrations
{
    [DbContext(typeof(CountryContext))]
    partial class CountryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OlympicGames.Models.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "in",
                            Name = "Indoor"
                        },
                        new
                        {
                            CategoryID = "ou",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlagImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("GameID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "can",
                            CategoryID = "in",
                            FlagImage = "canada.jpg",
                            GameID = "wo",
                            Name = "Canada"
                        },
                        new
                        {
                            CountryID = "swe",
                            CategoryID = "in",
                            FlagImage = "sweden.jpg",
                            GameID = "wo",
                            Name = "Sweden"
                        },
                        new
                        {
                            CountryID = "gb",
                            CategoryID = "in",
                            FlagImage = "great_britain.jpg",
                            GameID = "wo",
                            Name = "Great Britain"
                        },
                        new
                        {
                            CountryID = "jam",
                            CategoryID = "ou",
                            FlagImage = "jamaica.jpg",
                            GameID = "wo",
                            Name = "Jamaica"
                        },
                        new
                        {
                            CountryID = "ita",
                            CategoryID = "ou",
                            FlagImage = "italy.jpg",
                            GameID = "wo",
                            Name = "Italy"
                        },
                        new
                        {
                            CountryID = "jap",
                            CategoryID = "ou",
                            FlagImage = "japan.jpg",
                            GameID = "wo",
                            Name = "Japan"
                        },
                        new
                        {
                            CountryID = "ger",
                            CategoryID = "in",
                            FlagImage = "germany.jpg",
                            GameID = "so",
                            Name = "Germany"
                        },
                        new
                        {
                            CountryID = "chi",
                            CategoryID = "in",
                            FlagImage = "china.jpg",
                            GameID = "so",
                            Name = "China"
                        },
                        new
                        {
                            CountryID = "mex",
                            CategoryID = "in",
                            FlagImage = "mexico.jpg",
                            GameID = "so",
                            Name = "Mexico"
                        },
                        new
                        {
                            CountryID = "bra",
                            CategoryID = "ou",
                            FlagImage = "brazil.jpg",
                            GameID = "so",
                            Name = "Brazil"
                        },
                        new
                        {
                            CountryID = "net",
                            CategoryID = "ou",
                            FlagImage = "netherlands.jpg",
                            GameID = "so",
                            Name = "Netherlands"
                        },
                        new
                        {
                            CountryID = "usa",
                            CategoryID = "ou",
                            FlagImage = "united_states.jpg",
                            GameID = "so",
                            Name = "USA"
                        },
                        new
                        {
                            CountryID = "tha",
                            CategoryID = "in",
                            FlagImage = "thailand.jpg",
                            GameID = "pa",
                            Name = "Thailand"
                        },
                        new
                        {
                            CountryID = "uru",
                            CategoryID = "in",
                            FlagImage = "uruguay.jpg",
                            GameID = "pa",
                            Name = "Uruguay"
                        },
                        new
                        {
                            CountryID = "ukr",
                            CategoryID = "in",
                            FlagImage = "ukraine.jpg",
                            GameID = "pa",
                            Name = "Ukraine"
                        },
                        new
                        {
                            CountryID = "aus",
                            CategoryID = "ou",
                            FlagImage = "austria.jpg",
                            GameID = "pa",
                            Name = "Austria"
                        },
                        new
                        {
                            CountryID = "pak",
                            CategoryID = "ou",
                            FlagImage = "pakistan.jpg",
                            GameID = "pa",
                            Name = "Pakistan"
                        },
                        new
                        {
                            CountryID = "zim",
                            CategoryID = "ou",
                            FlagImage = "zimbabwe.jpg",
                            GameID = "pa",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            CountryID = "fra",
                            CategoryID = "in",
                            FlagImage = "france.jpg",
                            GameID = "yog",
                            Name = "France"
                        },
                        new
                        {
                            CountryID = "cyp",
                            CategoryID = "in",
                            FlagImage = "cyprus.jpg",
                            GameID = "yog",
                            Name = "Cyprus"
                        },
                        new
                        {
                            CountryID = "rus",
                            CategoryID = "in",
                            FlagImage = "russia.jpg",
                            GameID = "yog",
                            Name = "Russia"
                        },
                        new
                        {
                            CountryID = "fin",
                            CategoryID = "ou",
                            FlagImage = "finland.jpg",
                            GameID = "yog",
                            Name = "Finland"
                        },
                        new
                        {
                            CountryID = "slo",
                            CategoryID = "ou",
                            FlagImage = "slovakia.jpg",
                            GameID = "yog",
                            Name = "Slovakia"
                        },
                        new
                        {
                            CountryID = "por",
                            CategoryID = "ou",
                            FlagImage = "portugal.jpg",
                            GameID = "yog",
                            Name = "Portugal"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "wo",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameID = "so",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameID = "pa",
                            Name = "Paralympic Games"
                        },
                        new
                        {
                            GameID = "yog",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("OlympicGames.Models.Country", b =>
                {
                    b.HasOne("OlympicGames.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlympicGames.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID");

                    b.Navigation("Category");

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
